# Description: QT5 Base - Core non-graphical classes used by other modules.
# URL: http://qt-project.org/doc/qt-5.0/qtcore/qtcore-index.html

name=snowshoe
version=gita45bd95
release=1
source=(sftp://tmdssk3358-team@ixonos01.novipark.dk/source/$name-$version.tar.gz
        snowshoe-fullscreen.patch
        snowshoe.service)
depends=(qtwebkit)

build() {
   cd $name-$version

   patch -p1 < $SRC/snowshoe-fullscreen.patch

   # Set up environment for qmake
   PATH=$SYSROOT/opt/qt5-native/bin:$PATH
   export QMAKESPEC=$SYSROOT/opt/qt5-native/mkspecs/linux-arm-gnueabi-g++

   qmake -r
   make -j $JOBS

   make INSTALL_ROOT=$PKG install

   install -Dm644 $SRC/snowshoe.service $PKG/etc/systemd/system/snowshoe.service
}
