# Description: QT5 Base - Core non-graphical classes used by other modules.
# URL: http://qt-project.org/doc/qt-5.0/qtcore/qtcore-index.html

name=qtwebkit
version=5.1.0
release=1
source=(http://download.qt-project.org/official_releases/qt/${version%.*}/$version/submodules/$name-opensource-src-$version.tar.xz
        fix-compilation.patch)
depends=(qtbase qtjsbackend qtdeclarative)

build() {
   cd $name-opensource-src-$version

   patch -p2 -i $SRC/fix-compilation.patch

   # Set up environment for qmake
   PATH=$SYSROOT/opt/qt5-native/bin:$PATH

   qmake -r
   make -j $JOBS

   # Install in a temp folder to ease cleanup
   make INSTALL_ROOT=$PKG/tmp install

   # The files are installed with SYSROOT as prefix. Move to root of PKG
   mv $PKG/tmp/$SYSROOT/* $PKG

   # Clean SYSROOT prefix path
   rm -rf $PKG/tmp

   # Fix libtool files
   fix_la_files $PKG
}
