# Description: QT5 webkit examples
# URL: http://qt-project.org/doc/qt-5.0/qtwebkitexamples/qtwebkitexamples-index.html

name=qtwebkit-examples
version=5.1.1
release=1
source=(http://download.qt-project.org/official_releases/qt/${version%.*}/$version/submodules/$name-opensource-src-$version.tar.xz)
depends=(qtwebkit qtxmlpatterns qtquick1)

build() {
   cd $name-opensource-src-$version

   # Set up environment for qmake
   PATH=$SYSROOT/opt/qt5-native/bin:$PATH

   qmake -r
   cd examples
   make -j $JOBS

   # Install in a temp folder to ease cleanup
   make INSTALL_ROOT=$PKG/tmp install

   # The files are installed with SYSROOT as prefix. Move to root of PKG
   mv $PKG/tmp/$SYSROOT/* $PKG

   # Clean SYSROOT prefix path
   rm -rf $PKG/tmp

   # Fix libtool files
   fix_la_files $PKG
}
