# Description: QT5 Base - Core non-graphical classes used by other modules.
# URL: http://qt-project.org/doc/qt-5.0/qtcore/qtcore-index.html

name=qtbase
version=5.0.2
release=1
source=(http://download.qt-project.org/official_releases/qt/${version%.*}/$version/submodules/$name-opensource-src-$version.tar.xz
        qmake-is-already-built.patch)
depends=(zlib libpng libjpeg harfbuzz freetype glib libpcre sqlite ti-graphics-sdk icu
         gst-plugins-good-0.10 gst-ffmpeg-0.10)

build() {
   cd qtbase-opensource-src-$version

   # Create qmake configuration
   QMAKESPEC="mkspecs/linux-g++/qmake.conf"
   echo "QMAKE_CC = $HOST-gcc" >> $QMAKESPEC
   echo "QMAKE_CXX = $HOST-g++" >> $QMAKESPEC
   echo "QMAKE_LINK = $HOST-g++" >> $QMAKESPEC
   echo "QMAKE_LINK_SHLIB = $HOST-g++" >> $QMAKESPEC
   echo "QMAKE_AR = $HOST-ar cqs" >> $QMAKESPEC
   echo "QMAKE_OBJCOPY = $HOST-objcopy" >> $QMAKESPEC
   echo "QMAKE_STRIP = $HOST-strip" >> $QMAKESPEC

   echo "QMAKE_INCDIR_OPENGL_ES2=$SYSROOT/usr/include/OGLES2" >> $QMAKESPEC
   echo "QMAKE_INCDIR_EGL=$SYSROOT/usr/include/OGLES2" >> $QMAKESPEC

   ./configure -prefix /opt/qt5 \
               -hostprefix /opt/qt5-native \
               -xplatform linux-g++ \
               -release \
               -opensource \
               -confirm-license \
               -optimized-qmake \
               -no-xcb \
               -no-pch \
               -icu \
               -system-sqlite \
               -nomake tests \
               -nomake examples \
               -nomake demos \
               -no-rpath \
               -verbose \
               -opengl es2 \
               -eglfs

   make -j $JOBS
   make INSTALL_ROOT=$PKG install

   echo -e "[Paths]\nPrefix=$SYSROOT/opt/qt5\nHostPrefix=$SYSROOT/opt/qt5-native" > bin/qt.conf

   install -Dm644 bin/qt.conf $PKG/opt/qt5-native/bin/qt.conf

   # Fix libtool files
   fix_la_files $PKG
}
