# Description: QT5 Base - Core non-graphical classes used by other modules.
# URL: http://qt-project.org/doc/qt-5.0/qtcore/qtcore-index.html

name=qtbase
version=5.0.2
release=1
source=(http://download.qt-project.org/official_releases/qt/${version%.*}/$version/submodules/$name-opensource-src-$version.tar.xz
        qmake-is-already-built.patch)
depends=(zlib libpng libjpeg harfbuzz freetype glib libpcre sqlite ti-graphics-sdk icu
         gst-plugins-good-0.10 gst-ffmpeg-0.10)

build() {
   cd qtbase-opensource-src-$version

   sed -i "s|arm-linux-gnueabi|$HOST|g" mkspecs/linux-arm-gnueabi-g++/qmake.conf
   echo "QMAKE_INCDIR_OPENGL_ES2=$SYSROOT/usr/include/OGLES2" \
        >> mkspecs/linux-arm-gnueabi-g++/qmake.conf
   echo "QMAKE_INCDIR_EGL=$SYSROOT/usr/include/OGLES2" \
        >> mkspecs/linux-arm-gnueabi-g++/qmake.conf

   ./configure -prefix /opt/qt5 \
               -hostprefix /opt/qt5-native \
               -xplatform linux-arm-gnueabi-g++ \
               -release \
               -opensource \
               -confirm-license \
               -no-xcb \
               -no-pch \
               -icu \
               -system-sqlite \
               -nomake examples \
               -nomake test \
               -verbose \
               -opengl es2 \
               -eglfs \
               -optimized-qmake

   make -j $JOBS
   make INSTALL_ROOT=$PKG install

   echo -e "[Paths]\nPrefix=$SYSROOT/opt/qt5\nHostPrefix=$SYSROOT/opt/qt5-native" > bin/qt.conf

   install -Dm644 bin/qt.conf $PKG/opt/qt5-native/bin/qt.conf

   # Fix libtool files
   fix_la_files $PKG
}
