# Description: QT5 Declarative - Provided for Qt 4 compatibility. See QT Quick.
# URL: http://qt-project.org/doc/qt-4.8/qtquick.html

name=qtdeclarative
version=5.1.1
release=1
source=(http://download.qt-project.org/official_releases/qt/${version%.*}/$version/submodules/$name-opensource-src-$version.tar.xz
        qmltestrunner-fix-link.patch)
depends=(qtbase qtjsbackend)

build() {
   cd $name-opensource-src-$version

   patch -p2 < $SRC/qmltestrunner-fix-link.patch

   # Set up environment for qmake
   PATH=$SYSROOT/opt/qt5-native/bin:$PATH

   qmake -r
   make -j $JOBS

   # Install in a temp folder to ease cleanup
   make INSTALL_ROOT=$PKG/tmp install

   # The files are installed with SYSROOT as prefix. Move to root of PKG
   mv $PKG/tmp/$SYSROOT/* $PKG

   # Clean SYSROOT prefix path
   rm -rf $PKG/tmp

   # Fix libtool files
   fix_la_files $PKG
}
